<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Desafio2_DES.DAL\Desafio2_DES.DAL.csproj" />
    <ProjectReference Include="..\Desafio2_DES.Entities\Desafio2_DES.Entities.csproj" />
  </ItemGroup>

</Project>
